### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#11]
Is there any plan to integrate GDPR with the framework or any suggestion ? 
There are different package that can make but I really like the logic of your framework and have something integrated in same way would be great! :)

Thanks!

**Comment by ocram** [comment]
What are you referring to exactly?

GDPR is not something you can simply “integrate” with a library. And it’s not even the duty of the library to ensure compliance. Instead, it’s a requirement for your business and you have to have documentation, processes and best practices in place.

What a library *can* do, of course, is making compliance as easy as possible for you. Well, that’s certainly what this framework and the individual libraries seem to be doing. Without further research, I think the authentication component is the only component that processes personal data, and it stores all its data in the database. So you know where to look for the data you’re storing.

**Comment by daebak74** [comment]
My mistake, not clear question. By the way my meaning WASN'T full procedure but for cookie and Privacy just because I have seen your Privacy Policy well done. Great Job!

BUT YOU ARE RIGHT! what need Server Side is already well done and show, accept, reject, required or optional and so on are action client side so out of the scope of the framework. 

Sometimes the tired mind makes bad jokes and obvious things seem different. I appreciate the work, the professional support that you offer and I like to interact because in addition to being helpful for me and others can offer new ideas. But if it's a problem, I avoid it.

Thanks.

**Comment by ocram** [comment]
No problem. It’s fine, of course. We already have *two* open issues now in this repository that need to be addressed soon. So these have definitely been valuable contributions. And discussing things never hurts. Often bugs are found where nobody expected them.

The library for the privacy policy has been one attempt to implement a large part of the documentation. But this is totally separate from this framework.
