### ISSUE TITLE
Check if a template exist.

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#13]
Hi,
I try to check if a mail template in current language exist or fallback in default language. 

there is some way ? :) something as symfony...

$mail_template = '$fallback_lang .'/template.html.twig';
if ( $app->get('templating')->exists($lang .'/template.html.twig') ) {
    $mail_template = '$lang .'/template.html.twig';
}

Other point dump in template for example {{ dump (user) }} ?

Thanks!

**Comment by ocram** [comment]
Excellent points, thanks!

Regarding the first one: Please use `composer update delight-im/foundation-core` to update this framework to version `v4.3.0` and [you’ll be able to](https://github.com/delight-im/PHP-Foundation-Core/commit/08e630b7197f7a80efa0cce221f7c75dc54ca9ac) catch `\Delight\Foundation\Throwable\TemplateNotFoundError` whenever you try to load a template from `views` which does not actually exist. That should work for your use case:

```php
try {
    echo $app->view('mail_' . $lang . '.html.twig');
}
catch (\Delight\Foundation\Throwable\TemplateNotFoundError $e) {
    echo $app->view('mail_' . $fallback_lang . '.html.twig');
}
```

Of course, you should make sure that directory traversal attacks are not possible, i.e. that your language variables really contain only characters you’d expect.

As for the second point: You’ll also [need](https://github.com/delight-im/PHP-Foundation-Core/commit/eb45c53bcd3087f2efdb3ecfd212456eec20be5e) `v4.3.0`, and when setting your application to debugging mode via `APP_DEBUG=1`, you’ll be able to use the `dump` function in your templates.

**Comment by daebak74** [comment]
Work great! 👍 
Thanks.
