### ISSUE TITLE
Check if a file exist in template.

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#14]
Hi 
same as if a template exist now I have problem into template. I need to include a file js if exist.

example check if a i18n file of a plugin exist in selected language or fallback default language
but same can be a photo photo or placeholder anyway
 
- header.html.twig

```
{%if app.url('/assets/plugin/js/i18n/'~ session.lang ~'.js') %}
<script src="{{ app.url('/assets/plugin/js/i18n/'~ session.lang ~'.js') }}"></script>
{% else %}
<script src="{{ app.url('/assets/plugin/js/i18n/'~ session.fallback_lang ~'.js') }}"></script>
{% endif %}
```
this if statement doesn't work if session.lang.js doesn't exist brb a 404 code.

I was thinking to use a $app->getTemplateManager()->addFilter function with file_exist and in template return the file but seems a strange way :)

Thanks.

**Comment by ocram** [comment]
Unfortunately, this is not as easy as it has been with the template files.

While the template files must simply exist on your local file system, the URLs generated by `App#url` and (on request) handled by the web server pass through routing. The response may either be a file on the local file system (in the `public` folder) or a route processed by your PHP application.

So there’s much more complexity here already.

If you wanted to check if the URL you’re generating with `App#url` resulted in a `404` status, you would have to send an HTTP request (that stays on the local host) for every single check. Generating and handling HTTP requests for simple checks that may be used often is not really efficient.

If you wanted to avoid sending those HTTP requests while still being able to know if *any* URL actually exists (e.g. with a `200` status), you’d have to *simulate* those requests, at least, passing through your routing.

All this is probably something one wants to avoid. So what remains is the possibility to check for (static) files that exist in the `public` directory, where your JS files are usually stored, too.

From the perspective of `app/index.php`, the URL expressed by

```
app.url('/assets/plugin/js/i18n/' ~ session.lang ~ '.js')
```

is in

```
__DIR__ . '/../public/assets/plugin/js/i18n/' . $session->lang . '.js'
```

so why not try to write a simple function (passed to Twig) which does this, just as you suggested?

Again, make sure to implement this safely, not allowing for arbitrary path traversals. Your language code can probably be `[A-Za-z_-]+` only.

**Comment by daebak74** [comment]
Wow tis path traversal I didn't think but shouldn't... I hope :) anyway my thinking was this I didn't try but should work if $app->url($toPath) return true or false... should.

app/index.php

```
$app->getTemplateManager()->addFilter('ifFileExist', function ($file) {
    return $app->url($file);
});
```

footer.html.twig

```
{% set file = '/assets/plugin/js/i18n/' ~ session.lang ~ '.js' %}

{% if file ifFileExist %}
<script src="{{ app.url(file) }}"></script>
{% else %}
<script src="{{ app.url('/assets/plugin/js/i18n/'~ session.fallback_lang ~'.js') }}"></script>
{% endif %}
```
I am out or ... ? :)

Thanks.

**Comment by ocram** [comment]
Well, with something like this, which only checks for a file’s existence, a directory traversal attack will not have that much of an impact. But if you implement something where the user can actually *include* files, you should really check if they are allowed to access or include that file.

Regarding your implementation here, `App#url` does not return `true` or `false`. It *always* returns a URL for the input you have specified, no matter if that URL “exists” or not. That’s exactly how you have used it in the templates as well. Why do you expect it to behave differently in the application code? So, again, the return value

```php
return $app->url($file);
```

won’t help you and doesn’t make much sense.

As suggested earlier, it would have to be something like this:

```php
return file_exists(__DIR__ . '/../public/' . ltrim($file, '/'));
```

But this has not been tested, and you must use it securely, as explained earlier. User inputs must never be fed into this function. If they are, you have to ensure the user did not specify something like `/../../../../../some/secret/file/that/the/user/must/not/know/exists`, etc.
