### ISSUE TITLE
Wildcard routing

### ISSUE THREAD

**Issue by bleutzinn** [delight-im/PHP-Foundation#19]
As usual I have an awkward use case, or so it seems. I'm using PHP-Foundation and I think I need some kind of wild card routing. Let me explain why.

[Coast CMS](http://coast-cms.de) is a static site or static web page editor which I love for it's wonderful user interaction. However, the code base is dated and security isn't optimal.

My intention is to recreate Coast CMS using a modern and solid framework: PHP Foundation.

The issue is this: Coast CMS does not require any modification of a static web page. When a user is logged in it simple injects additional CSS and JS to make certain parts of the page content editable.

By using a route like this in `/App/index.php`:
```
$app->get('/:page', ['\App\ShowSitePageController', 'showPage']);
```
I can process a HTML page and also any other file like an image which are at the same directory level as the page. The problem is that all other files in sub directories are not routed. That's why I'm wondering about wildcard routing, like for instance:
```
$app->get('/:page/*.*', ['\App\ShowSitePageController', 'showPageResource']);
```

To separate the framework and the static site ideally I would like to have this file structure:
```
cms/
index.html
about.html
images/logo.png
```
where the framework is in `cms/` and the other three files make the static site. This structure, I concluded, is not possible.

Second best is this structure:
```
site/
site/index.html
site/about.html
site/images/logo.png
app/
index.php
... all other framework files
```
where the static site is in it's own directory named `site`.

With the wildcard router one could simply route `/about.html` and all accompanying CSS files and images and have the controller fetch them from the `site` directory.

I fear this is currently not supported, in which case this is a feature request.

**Comment by ocram** [comment]
The router is built around forward slashes as the separators between path segments, as you can see [here](https://github.com/delight-im/PHP-Router/blob/74c4ced1edad538b7567c11b7f18722a76c1de97/src/Router.php):

```php
/** Regular expression used to find named parameters in routes */
const REGEX_PATH_PARAMS = '/(?<=\/):([^\/]+)(?=\/|$)/';
/** Regular expression used to match a single segment of a path */
const REGEX_PATH_SEGMENT = '([^\/]+)';
```

If you don’t want that, you could change those two constants.

Or you could work with `Router#getRootPath` and `Router#getRoute` directly and decide based on that, without defining routes for the router in the first place.

These are also available via `App#currentRoute` (also: `App#getRequestMethod`).

Finally, you could work with `$_SERVER['REQUEST_URI']` directly.

All these solutions would leave out the root definitions in your `index.php` and just do something based on the variables and methods listed above. The two `App` methods should probably be the most helpful.

When it comes to your different directory structure, this should (both) be possible by adjusting the routing in the `.htaccess` (in the single section named “Routing”).

> When a user is logged in it simple injects additional CSS and JS to make certain parts of the page content editable.

But it writes back to the files on the server, right? So there must be some actual (server-side) authentication *somewhere*.

**Comment by bleutzinn** [comment]
Thanks for your help on this.

For the purpose of these issues also being a kind of knowledge base I'd like to share how I solved it.

The directory structure is exactly what I wanted in the first place:
```
steckelfish/
draft/index.html
draft/about.html
draft/images/logo.png
index.html
about.html
images/logo.png
```

The PHP-Foundation app is in the `steckelfish/` directory while the `draft/` directory holds draft versions of pages that can (in future) be published to the site root once they are ready to go public. Of course the editing of draft pages and the publish action is only allowed to logged in users/authors.

The site root is not the webserver document root and to get this setup these are the configuration settings:

In `steckelfish/config/.env`:
```
# The public HTTP(S) URL pointing at the application's root directory
APP_PUBLIC_URL=http://localhost/sf2-dev/
```

BTW this site root URL is available in PHP through `$app->url('/')` and in a Twig template as `app.url('/')`.

The `.htaccess` file, normally in the framework directory (`steckelfish/` in this case) is moved one level up, so it is in `sf2-dev/`. This is in the section “Routing”:
```
# Do not rewrite physical files with the exception of
# directories and HTML files in the draft directory
RewriteCond %{REQUEST_FILENAME} -f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^(.*)/draft/.*\.html$
RewriteRule . - [L]

# And let 'index.php' handle everything else
RewriteRule . steckelfish/index.php [L]
```

Now the routing is pretty straightforward. I looked at the regular expressions at [PHP-Router#17](https://github.com/delight-im/PHP-Router/blob/74c4ced1edad538b7567c11b7f18722a76c1de97/src/Router.php#L17) as you pointed out but going that route is way over my head. So these are the routes in `steckelfish/app/index.php` is like this:
```
$app->get('/draft', [ '\App\DraftPageController', 'showIndex' ]);
$app->get('/draft/', [ '\App\DraftPageController', 'showIndex' ]);
$app->get('/draft/:page', [ '\App\DraftPageController', 'showPage' ]);
```

Again thank you for your help.

**Comment by ocram** [comment]
> For the purpose of these issues also being a kind of knowledge base I'd like to share how I solved it.

This is very much appreciated, thank you!

Regarding your solution, what you write all makes sense and looks good.

> I looked at the [regular expressions](https://github.com/delight-im/PHP-Router/blob/74c4ced1edad538b7567c11b7f18722a76c1de97/src/Router.php#L17) as you pointed out but going that route is way over my head.

Changes to these regular expressions would only have been required because you said you need forward slashes (which are not URL-encoded either) in (the variable parts of) your routes.

**Comment by bleutzinn** [comment]
My pleasure! I would love to see your framework being used more. Explaining my use case is my way of contributing.

Regarding the initially required wildcards in routes, these are actually not needed in my case. This use case mimics the workings of Coast CMS which requires all HTML pages to be in the site root. So there are no sub directories below `draft/`. This let me off the hook.
