### ISSUE TITLE
Error in HomeController when publish online

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#22]
I tried to move my local project online now the php version is 7.1 and I have the same issue as we spoke here #4 

app/index.php

```
<?php

	use Delight\Foundation\App;
	
	//$app->get('/', '\App\HomeController::getIndex');
	
	$app->get('/', '\App\Controllers\HomeController::getIndex');
```
	
this work -> $app->get('/', '\App\HomeController::getIndex');

if I try to move this file into app\controllers\ 

$app->get('/', '\App\Controllers\HomeController::getIndex');

and my HomeController.php

```
namespace App\Controllers;
    
    use Delight\Foundation\App;
    
    class HomeController {
    	public static function getIndex(App $app) {
    		echo('Hi');
    	}
    }
```
receive the error

InvalidArgumentException: Invalid callback for methods `get` at route `/` in file /home/ezgestit/public_html/vendor/delight-im/router/src/Router.php on line 264
Stack trace:
  1. InvalidArgumentException->() /home/ezgestit/public_html/vendor/delight-im/router/src/Router.php:264
  2. Delight\Router\Router->addRoute() /home/ezgestit/public_html/vendor/delight-im/router/src/Router.php:63
  3. Delight\Router\Router->get() /home/ezgestit/public_html/vendor/delight-im/foundation-core/src/App.php:750
  4. Delight\Foundation\App->get() /home/ezgestit/public_html/app/index.php:7
  5. require() /home/ezgestit/public_html/index.php:118

Where I am in wrong ?

Thanks!

**Comment by daebak74** [comment]
My faults Damn windows the directory name is in Lower Case controllers and not Controllers.

**Comment by ocram** [comment]
No problem, thanks for sharing the cause of the error!
