### ISSUE TITLE
Question a light CMS to integrate with the framework

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#23]
I like this framework more and more every day. :)

I don't wanna build a CMS be clear. There are ton around the web :) I would just give a support in my app for manage the content for the frontend part. Thanks for the flexibility of the system I started to write my own solution but I have a question.
Maybe is there some libraries that could be integrated with the framework ?

Thanks.

**Comment by daebak74** [comment]
Forget my question and sorry for it. Cause most of the cms are based on some framework so nothing continue my solution. Some time too many hours let the mind to go in strange directions :)

**Comment by ocram** [comment]
No problem, thanks!
