### ISSUE TITLE
Warning: zend.assertions

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#26]
If debug is disabled show this warning:

Warning: zend.assertions may be completely enabled or disabled only in php.ini in \index.php on line 49

I read in php that is a bug and can't be set as -1 by the way seems on php 7.0 zend.assertions is ignored.

**Comment by ocram** [comment]
Thanks!

That’s strange. As you can see in `/index.php`, when setting `zend.assertions`, the call to `\ini_set` is preceded by an `@`, so there shouldn’t be any warning displayed.

**Comment by ocram** [comment]
Do you have the latest version of that file?

If not, can you check what the differences are, and whether you can safely upgrade?

**Comment by daebak74** [comment]
Yes, I didn't update latest. As you said `@` missed in my version addied it and no any warning.
