### ISSUE TITLE
Show db content in template using insert tags.

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#27]
My intent is to give flexibility in creating the frontend using tags to insert content. For example insert the article saved in db with id 1. The solution that comes to mind is to use custom filter for example

`{{ '1' | articles }}`

But if I save a block of template in db TEXT field for example 

`<div class="myarticle">{{ '1' | articles }}</div>`

or for example store in text html editor to customize results? for example

`<p>Dear Mr. {{ '1::firstname' | user }}</p>`

doesn't work.

How I can fix it ? thanks. 
I always like your answer and comment in my post and from other user because are linear so I really appreciate to know from you if this is the right way or I have to use other approach.

Thanks.

**Comment by ocram** [comment]
You want an easier way to access database records from templates, right?

Well, right now, the recommended approach is to fetch database records in your controller classes and then just display that content in the views.

So you would have to fetch the records and assign to `$articles` in your controller and then pass that variable to your view.

If you want to access articles by ID, you could use the IDs from the database records as the keys in your array `$article`.

That would make something like `{{ articles.42 }}` or `{{ articles.first }}` possible.

Now the only problem may be that you don’t always want to write something like this in your controllers:

```php
$articles = $app->db()->select(
    "SELECT id, title, content, created_at FROM articles ORDER BY created_at DESC LIMIT 0, 10"
);
```

This is a separate problem. You could create methods or classes that provide shorthands to this.

Does that help?

**Comment by daebak74** [comment]
First at all thanks. yes this is how normally work pass in the view all the variable. But in this way I can access only in that specific page view and repeat the job in each view I need to access of those tables. for this I was thinking an custom filter. 

```
$app->getTemplateManager()->addFilter('articles', function ($id) {
 //...
});

$app->getTemplateManager()->addFilter('news', function ($id) {
 //...
});
```
For example I have 2 controller one for show all the CMS pages and one for manage the news and so on. 

If I wanna show news with the id 3 in page content home I just need to use {{ '3' | news }}. Maybe for one case seems senseless but for different tables give sense. For example I would to include a module to use inside a Page or a form and so on.

This approach if I use inside template work but if I store in db {{ '3' | news }} and than reload in template doesn't work.

In some cms they use insert tags as {{user :: 1}} or {{article :: 3}}.

Thanks.

**Comment by ocram** [comment]
Thanks for the additional details!

If this is how you generally fetch database records, but you want them to be available in all views, not just in a single view where you explicitly provided them, consider global variables instead. Just use `App#getTemplateManager#addGlobal` (see [documentation](https://github.com/delight-im/PHP-Foundation#templates)) to inject some variable (e.g. the list of your articles) into *all* views at once.

Alternatively, if you want to fetch by specific IDs, you could use `App#getTemplateManager#addFunction`.

But even your approach of using filters should work, although it’s perhaps not the ideal solution.

So you’re saying that `{{ '3' | news }}` works. But as soon as you’re storing it in your database and reload it stops working? What exactly are you storing in your database? That `{{ '3' | news }}` snippet? And you reload the page?

**Comment by daebak74** [comment]
Thanks I'll check your info and if in case I'll update. Than if I use {{'3'
| articles }} in template work I mean execyte the Custom filter.If I store
it in db in text field and than in template I call {{text | raw}} don't
execute the filter just print me out what I wrote. {{'3' | articles }}

Il Lun 2 Dic 2019, 19:06 Marco <notifications@github.com> ha scritto:

**Comment by ocram** [comment]
Is this what you are doing?

 1. You store `{{'3' | articles }}` as plain text in your database.
 1. You load the text `{{'3' | articles }}` from your database
 1. You include the text from the database in your view via `{{ text | raw }}`
 1. You expect the custom filter `articles` to be executed but instead `{{'3' | articles }}` is displayed as text

Is this correct?

If so, the behavior is correct and your assumptions are wrong. You would need for Twig what [`eval`](https://www.php.net/manual/en/function.eval.php) does in PHP. Or, better, store only the ID of the article in the database and try passing that to the custom filter.

**Comment by daebak74** [comment]
Yes is correct and I know that the the behavior is correct. No, I can't pass just the ID because can be article, news, modules, user and so on.. I can't guest.

**Comment by ocram** [comment]
```
{% if myType == 'article' %}
    {% myId | article %}
{% else if myType == 'news' %}
    ...
...
{% endif %}
```

Does this work?

Other than that, I don’t know if you really want the views to become that powerful and to have so many responsibilities, which should be somewhere else (e.g. in the controller) instead.

**Comment by daebak74** [comment]
:( nope doesn't help because what I need is what you wrote before but is not possible because I can't store in text field {{'3' | articles }} and waiting that in template process the custom filter as eval().

So or I let add {{'3' | articles }} only in the template view or adopt other syntax for example {{article::3}} and in the controller process a scan of text field and return in template view the article by is ID.
(Last solution is a concept I don't know yet how to do :P 

Anyway thanks I already made you lose so much time to answer my questions and I don't want to take more time.

**Comment by ocram** [comment]
Sorry, I don’t have any significantly better solutions for this specific use case.

What you could still try, however, is using `addFunction` instead. The parameters to your function, e.g. `article` and `3`, could be stored in the database and passed to the global function in the view at runtime.
