### ISSUE TITLE
Download a Base64 string as file without saving on server

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#28]
Hi,
I think I didn't understand well how to use the download helper. By ajax I send a image string base64 that I would to download without save in temp file to server this is my code.

```
$data = base64_decode($data);							
header('Content-type: image/png');
header('Content-Disposition: attachment; filename='. $post_filename .'.png');

$app->downloadContent($data, $post_filename .'.png', 'image/png');
```

The result in inspector show me the image but didn't download what is wrong ?

Thanks and Happy New Year! :)

**Comment by ocram** [comment]
Happy New Year!

First, are you actually sending data from JavaScript to the server which the server then simply sends back to the same client with a download prompt? So could you instead just save the file locally using JavaScript?

Regarding your implementation, there should be no need to set custom headers. So simply calling

```php
$app->downloadContent(
	base64_decode($data),
	$post_filename . '.png',
	'image/png'
);
```

should be enough.

Do `$data` and `$post_filename` really contain the data you expect?

Which browser are you running the example in?

**Comment by daebak74** [comment]
What I make as first thing but doesn't work so I got right your documentation how the helper work.
The browser is Chrome 79. Anyway in inspector result as result show me the image correct. Yes $post_filename and $data are correct because repeat in inspector show me the image but doesn't download anything :(

**Comment by daebak74** [comment]
this is my javascript:

```
$.ajax({
                url: "/tools",
                type: "post",
                dataType: "text",
                data: {
                    action: 'svga_download',
                    imgdata: b,
                    filename: h
                },
            })
```
This is what send parsed data

action: svga_download
imgdata: data:image/png;base64, .....
filename: svgA10222380761803795.png

and this is my php

```
 } elseif ($action === 'svga_download') { // SVG DOWNLOAD

				$post_filename = $app->input()->post('filename');
				$post_imgdata = $app->input()->post('imgdata', TYPE_RAW);

				if(($post_imgdata && strrpos( $post_filename, 'png', -3) !== false) || ($post_imgdata && strrpos($post_filename, 'svg', -3) !== false)) {

					if ( strrpos( $post_filename, 'png', -3 ) !== false ) {
						
						list( $type, $data ) = explode( ';', $post_imgdata );
						list( $base, $data ) = explode( ',', $data );

						if ($type === 'data:image/png' && $base === 'base64') {

							$data = base64_decode($data);
							
							//header('Content-type: image/png');
							//header('Content-Disposition: attachment; filename='. $post_filename .'.png');

							//header('Content-Description: File Transfer');
							//header('Content-type: application/octet-stream');
							//header('Content-disposition: attachment; filename='. $post_filename .'.png');

							//echo($data);

							$app->downloadContent($data, $post_filename .'.png', 'image/png');

							
						}
					}

				}

			}
```
I think is correct but doesn't work :(

**Comment by daebak74** [comment]
I can't save it locally by javascript to avoid browser compatibility issues. 
By the way I can't use a get request and send the string. 

With a post request I think is impossible to download without save it on server so the solution that I use is:

1. store the file in a temp folder. 
2. On Ajax response success I download the file and delete it. 

If no other solution that let me download without create a temp file please close this post.

Thanks for your support.

**Comment by ocram** [comment]
A POST request works fine for downloads in general, but some user agents (rightly) prefer GET requests for downloads, and some even reject downloads coming from a POST request because they cannot be safely repeated (being non-idempotent).

Are you trying to send the download as a response to the AJAX request itself? That won’t work, and may be the reason for this issue. It must be the main request (e.g. a redirect) that is answered with a download response. Your AJAX response could, however, tell you do redirect to the download URL and you apply that redirect using JavaScript.

**Comment by daebak74** [comment]
> Your AJAX response could, however, tell you do redirect to the download URL and you apply that redirect using JavaScript.

Yes, same as my solution. Thanks!

**Comment by ocram** [comment]
This is the only solution that can work. If you don’t want to store the file on the server temporarily, you would have to send the data with the main request, not with an AJAX request in advance.
