### ISSUE TITLE
Add or omit parameter in url

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#29]
HI,
I have a question to improve the organization of route for my CMS. All the pages are selected by their unique alias and in case of multi language site I store the lang code with a fallback language.

So the route is simple

`$app->get('/:lang/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']);`
(www.domain.com/en/home)

So in controller I check if exist lang if not I select the one as fallback.

But if is not required a multi languages site how I can omit the lang in url and let accept www.domain.com/home ?

I was thinking to add a checkbox 'multi language' in BE so when the user create the root page and wanna show the lang in url just select it and verify it in Controller but I think that is a 
unnecessary operation maybe there is a direct way without this checkbox.

Maybe

`$app->get('/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']);`
`$app->get('/:lang/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']);`

But How I can check it using the same controller ?

Thanks.

**Comment by ocram** [comment]
A great way to avoid the issue of optional language identifiers in the path of URLs is to put the optional language identifier into the query string instead.

That way, `/:alias` can be requested as both `/myAlias` and `/myAlias?lang=myLang`. To the user, this doesn’t make any difference, and if you care about search engines, this is fine from a SEO perspective as well, but the downside is that Google can’t partition your pages into separate language sites as it does for subdomains or path segments. There are [tags and attributes](https://support.google.com/webmasters/answer/182192) that help you annotate your language-specific pages correctly, though. The methods `App#urlWithLang` and `App#currentUrlWithLang` can help with that. Full I18N support is [built-in](https://github.com/delight-im/PHP-Foundation#internationalization-i18n-and-localization-l10n).

If you really want the path segment, one other way is to *require* the language identifier and redirect the empty path to the most likely (or default) locale. This is harder to do for existing sites, of course.

Finally, you can use language-specific subdomains, which have some [support by this framework](https://github.com/delight-im/PHP-Foundation#routing).

**Comment by daebak74** [comment]
Sorry for delay to answer but I met other problem. :( Seems interesting the suggestion that you gave me and I am sure that one will help me to fix the problem but maybe I make some mistake in write the code.

My goal is to pass the lang in the url as:
`www.domain.com/en/home`

The problem is that if I have a route 
`$app->get('/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']);`
this is consider "en" as alias.

The solution  should be to make a route as:
`$app->get('/:lang/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']);`
But if they build a website that is not required a multilanguage the url is
`www.domain.com/home`
and in this case the above route consider "home" as lang. 

I think that the included Internationalization (I18N) included in this framework I used well

```
$i18n = new \Delight\I18n\I18n([
		\Delight\I18n\Codes::DE_DE,
		\Delight\I18n\Codes::EL_GR,
		\Delight\I18n\Codes::EN_US,
		\Delight\I18n\Codes::ES_ES,
		\Delight\I18n\Codes::FR_FR,
		\Delight\I18n\Codes::IT_IT,
		\Delight\I18n\Codes::RU_RU,
		\Delight\I18n\Codes::ZH_CN
	]);
	
	$app->i18n()->setLocaleManually(strtoupper($_SESSION['LANGUAGE']));
```

But what a sitemap expects is something like
```
www.domain.com/en/home
www.domain.com/de/home
```

I repeat maybe there is something that I missed from your suggestion but I didn't get I to solve it.

Thanks.

**Comment by ocram** [comment]
Everything you write is correct. But I think I’ve answered almost all of the questions in the previous comment already:

If you want to have the locale code in the paths as the first segment, your understanding of the routing and its problems are correct. What I suggested is you could redirect the empty path and other cases where the locale code is missing to the version of the route that *has* the locale code.

Apart from that, I suggested you could use the query string instead of the path to supply locale codes. The query string is really *made* for optional arguments, and it works fine out of the box.

Further, with the I18N component, setting

```php
$app->i18n()->setLocaleManually(strtoupper($_SESSION['LANGUAGE']));
```

does what it says: It provides a locale code manually, which is supposed to be stored in the session field `LANGUAGE`. So for that solution, you don’t even need the path segments or query parameters. That would work great with some language setting or drop-down list, where the user can select and apply the language manually.

If you only want it to pick up the locale automatically, e.g. from the path or query string, you could simply use

```php
$app->i18n()->setLocaleAutomatically();
```

Finally, having a separate *subdomain* instead of first path segment for each locale is another great solution. It works out of the box as well.

**Comment by daebak74** [comment]
Hi,
first at all thanks for your reply. I always appreciate to read you!

Use subdomain en.domain.com or de.domain.com is the first option that I offer and the working way it's pretty clear.

But as I wrote I would to offer the possibility to use lang in url domain.com/en/ not because I like to complicate my life but for different reason for example if the subdomain is used for other scope. (store.domain.com/en).

> So for that solution, you don’t even need the path segments or query parameters. That would work great with some language setting or drop-down list, where the user can select and apply the language manually.

This is what I am using in Backend where a "select menu" set the language and save it in session but for front end omit the lang in url is not a good solution.

Problem is SEO sitemap I couldn't to generate for different lang using the lang in url let me create a sitemap for each lang. 

Anyway I have this idea to solve the problem but I don't know if is crazy :) 

build the rout including the lang and leave the get parameter for the alias.
`
$app->get('/'. $app->i18n()->getLocale() .'/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']) && die();`

Of coarse the provided locale code is setted manually with a session language and a default fallback lang.

**Comment by ocram** [comment]
Thanks!

I see that you want to offer both subdomains and paths segments as two alternatives. Makes sense.

So subdomains have perfect support here and should be easy.

Path segments not so much. You probably have to find a workaround there, sorry. I wouldn’t use the solution you suggested where you put the locale code into the route definition. But there may be other solutions. The best solution I can come up with right now is the following:

Use the two route definitions that you already suggested, which map two routes to the same controller method:

```php
$app->get('/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']);
$app->get('/:locale/:alias', ['\App\Controllers\Frontend\Cms\Pages', 'getPage']);
```

And then detect which parameter is available and perhaps re-assign the variables if necessary:

```php
public static function getPage(App $app, $locale = null, $alias = null) {
    // if no parameter has been provided at all
    if (empty($locale)) {
        // TODO: error 404
        exit;
    }
    // if only one parameter has been provided
    elseif (empty($alias)) {
    	// the (first) parameter is not actually the locale but the alias
        $alias = $locale;
        // there has been no locale
        $locale = null;

        // TODO: use a default locale or auto-detect it
    }

    // TODO ...
}
```

Other than that, you should perhaps use query parameters. They work with sitemaps as well. You can link to your pages with different query parameters for different locale-specific versions, of course.

By the way, for subdomains, you might find it useful to list multiple possible domains (all the locale-specific subdomains and the main domain) in the configuration and then use `App#getCanonicalHost` to check which domain has been used. It’s explained [here](https://github.com/delight-im/PHP-Foundation#routing). Perhaps you’re already doing that.

**Comment by daebak74** [comment]
Perfect solution with this logic work great with more internal link as en/news/detail.

By the way for build how the core has to build link, sitemap or redirect is better to had in the table of db where are stored the root page 2 extra fields (locale (char5), multilang (tinyint1)).

Multilang if is enabled can let decide if use or omit the lang parameter in url. This remove the first get parameter (locale).

Maybe for build navigation link shouldn't be a problem because can be used relative path but for a script that generate a sitemap has to know if add or omit the lang parameter in url.

By the way You already gave me great suggestion so I close it because what can simplify the next step I can understand only later. :)

Thanks!

**Comment by ocram** [comment]
Glad that this would work for you – at least in solving the part of accepting routes, though not in generating the URLs for the routes.

To make this work better with more parameters, i.e. multiple placeholders in the route, I would further simplify my solution from above a little. And only the last parameter needs the `null` default value, because you either have *all* parameters or just *one* missing.

So that would be

```php
public static function getPage(App $app, $locale, $alias = null) {
    // if one parameter is missing (i.e. the locale has not been provided)
    if (empty($alias)) {
        // the parameters have to be shifted by one
        $alias = $locale;
        // there has been no locale
        $locale = null;

        // TODO: use a default locale or auto-detect it
    }

    // TODO ...
}
```

for a single placeholder in the route and

```php
public static function getPage(App $app, $locale, $alias, $foo, $bar = null) {
    // if one parameter is missing (i.e. the locale has not been provided)
    if (empty($bar)) {
        // the parameters have to be shifted by one
        $bar = $foo;
        $foo = $alias;
        $alias = $locale;
        // there has been no locale
        $locale = null;

        // TODO: use a default locale or auto-detect it
    }

    // TODO ...
}
```

for multiple placeholders in the route.

When generating URLs for the routes, you would then use either

```php
$app->url('/' . $app->i18n()->getLocale() . '/news');
// or
// $app->url('/' . $otherLocale . '/news');
```

or just

```php
$app->url('/news');
```

All in all, you could avoid a lot of complexity if (in addition to the subdomains) you would offer the query strings as an additional way to pass locale identifiers.

When accepting the requests, instead of checking for missing parameters and shifting the parameters, you would have to do *no work at all*. And when generating URLs for the routes, you could simply use the built-in methods `App#urlWithLang` and `App#urlWithParams`:

```php
// no locale:
$app->url('/news');

// current locale:
$app->urlWithLang('/news');

// other locale:
$app->urlWithParams('/news', [ 'lang' => $otherLocale ]);
```

**Comment by daebak74** [comment]
Great, great and great! :)
