### ISSUE TITLE
Integration with a Parse Server

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#33]
As I have said before, I like your way of programming and that's why I would like to receive your opinion. Having to use tables in common with different apps I was thinking of using a parse server with the framework and accessing through the PHP SDK. 

It's interesting to access data in different languages, the problem that seems less direct to me.

Let's say that on a separate server from the main app I create a db with data to share with other apps. 

Currently I can create $db and $dbw with a remote access restricted by IP and simply maintain a connection with a $dbw->app() ready to use from any controllers via the same function with any kind of query. I do not see same flexible way with the use of the rest API where I should to write code as

```
use Parse\ParseClient;

ParseClient::initialize( "APPLICATION_ID", "REST_KEY", "MASTER_KEY" );
ParseClient::setServerURL('url', '/');

use Parse\ParseException;
use Parse\ParseObject;

$myCustomObject = new ParseObject("MyCustomClassName");

$myCustomObject->set("myCustomKey1Name", "My custom value");
$myCustomObject->set("myCustomKey2Name", 999);

try {
  $myCustomObject->save();
  echo 'New object created with objectId: ' . $myCustomObject->getObjectId();
} catch (ParseException $ex) {

  echo 'Failed to create new object, with error message: ' . $ex->getMessage();
}
```
Or simple left join with condition that become long with equal or notequal in cascade.

What do you think about it and if any suggestion if I lost some part of that :)

Thanks.

**Comment by ocram** [comment]
So this seems to be mainly about Parse, which I don’t know, and not about this library here.

Please feel free to reopen this issue if you can make it more about this library, so that it becomes obvious which problems and questions are related to the project here.

**Comment by daebak74** [comment]
My intention was not to receive support but an opinion on logic. I believe that your db management is fantastic because it is flexible and fast. And as I wrote I think it is better than a system like that offered by a parse server that should be used to speed up development. The only thing I see positive and that's why I was looking for advice is finding a way of integration would open many fast development possibilities such as sharing data with other programming languages ​​up to the creation of CMS Rest API first.
Forgive me if I have gone on but I thought your opinion was useful.

**Comment by ocram** [comment]
Sure, got that, no problem. It’s just that the description of what exactly is the technical question was not very clear. To be honest, it’s still not clear enough, sorry. Could you give more details, or perhaps examples?

> system like that offered by a parse server that should be used to speed up development. The only thing I see positive and that's why I was looking for advice is finding a way of integration would open many fast development possibilities such as sharing data with other programming languages ​​up to the creation of CMS Rest API first.

So you want to speed up development through some integration? What integration? Integrating this library into a Parse application? How would that speed up development? Speed up your development in Parse?

And you want to share data with other programming languages? Sure, APIs, perhaps HTTP APIs and REST APIs are commonly used for that. What’s missing here in this project for you to be able to do this?
