### ISSUE TITLE
Error in HomeController

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#4]
I tried your update solution but rceive this error.

Whoops\Exception\ErrorException: Call to undefined function \App\HomeController::getIndex() in file Z:\ws\www\dsys\vendor\delight-im\router\src\Router.php on line 248
Stack trace:
  1. Whoops\Exception\ErrorException->() Z:\ws\www\dsys\vendor\delight-im\router\src\Router.php:248
  2. Delight\Router\Router->addRoute() Z:\ws\www\dsys\vendor\delight-im\router\src\Router.php:51
  3. Delight\Router\Router->get() Z:\ws\www\dsys\vendor\delight-im\foundation-core\src\App.php:526
  4. Delight\Foundation\App->get() Z:\ws\www\dsys\app\index.php:3
  5. () Z:\ws\www\dsys\index.php:94
  6. {main}() Z:\ws\www\dsys\index.php:0

**Comment by ocram** [comment]
What does your `app\index.php` file say, specifically on line 3?

The class `HomeController` and its method `getIndex` must exist within that same `app` folder and within the namespace `App`. The examples have this file. You can check it.

Does that help?

**Comment by daebak74** [comment]
I copy and paste your example from index.php and HomeController.php is the function that you wrote.

```
<?php

$app->get('/', '\App\HomeController::getIndex'); <- Line 3

// return an error page for undefined pages
$app->setStatus(404);
echo $app->view('404.html.twig');
```

**Comment by ocram** [comment]
Is `HomeController.php` actually in the same directory as your `index.php`? And does it have the exact name `HomeController.php`? Windows is case-insensitive, but it will be created with the case that you chose first. If you had `homecontroller.php` first and then renamed it to `HomeController.php`, that wouldn’t have changed anything. Finally, does it have exactly [this content](https://github.com/delight-im/PHP-Foundation/blob/9f6c3183b04bc035fb443cb1896ee92345aa4ab2/app/HomeController.php)?

**Comment by daebak74** [comment]
I am using your download file:

app/
- HomeController.php
- index.php

HomeController.php

```
<?php
namespace App;
use Delight\Foundation\App;
class HomeController {
	public static function getIndex(App $app) {
		// do something
		// ...
		// and return a view
		echo $app->view('welcome.html.twig', [
			'users' => [ 'Alice', 'Bob' ]
		]);
	}
}
```
index.php

```
<?php
$app->get('/', '\App\HomeController::getIndex');
$app->get('/greet/:name', '\App\IntroController::getGreet');
$app->post('/photos/:id/delete', '\App\PhotoController::postDelete');
// // OR USE CLOSURES (ANONYMOUS FUNCTIONS) DIRECTLY IN THIS FILE
//
// use Delight\Foundation\App;
//
// $app->get('/', function (App $app) {
// 	// do something
// 	// ...
//
// 	// and return a view
// 	echo $app->view('welcome.html.twig', [
// 		'users' => [ 'Alice', 'Bob' ]
// 	]);
// });
//
// $app->get('/greet/:name', function (App $app, $name) {
// 	// do something
// 	// ...
//
// 	// and return a view
// 	echo $app->view('greeting.html.twig', [
// 		'name' => $name,
// 		'greetingId' => $app->input()->get('greetingId', TYPE_INT)
// 	]);
// });
//
// $app->post('/photos/:id/delete', function (App $app, $id) {
// 	// do something
// 	// ...
// });
// return an error page for undefined pages
$app->setStatus(404);
echo $app->view('404.html.twig');
```
This is the line that give the problem.

$app->get('/', '\App\HomeController::getIndex');

If I use Anonymous Functions everything work well.

**Comment by ocram** [comment]
What PHP version are you on (both on your local machine and on the server)?

There may be a relevant [PHP bug](https://bugs.php.net/bug.php?id=68475), so perhaps that’s the reason.

As a workaround, instead of the current

```php
'\App\HomeController::getIndex'
```

can you use the following syntax?

```php
[ '\App\HomeController', 'getIndex' ]
// or
[ \App\HomeController::class, 'getIndex' ]
```

**Comment by daebak74** [comment]
Yes both works. 

By the way you are right I didn't think about it, the problem is the PHP Ver. 5.6.19 

With php 7 ->  '\App\HomeController::getIndex' 
Works!

**Comment by ocram** [comment]
That’s great, glad we could resolve this! And also thanks for testing this again.

PHP 5.6 is fine (apart from the fact that it reached EOL a month ago and isn’t supported anymore). This framework and our routing component declared support for PHP 5.6 but had examples that didn’t work in PHP 5.6, so that needed fixing.

The documentation for this framework has been fixed [here](https://github.com/delight-im/PHP-Foundation/commit/7fcf923065eab634dae2cf04b4c330494a81e33b).

So you can either keep PHP 5.6 and use the more traditional syntax or use PHP 7 and use the slightly shorter syntax.
