### ISSUE TITLE
Auth Process LockUp

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Foundation#9]
There is some solution for LockUp the account after X wrong attempts ? The LockUp can be 
temporary or permanent to be rehabilitated manually.

If notthis is my idea:

- New table login_attempts (tstamp, username, ip) where store the login attempts
- function checkbrute with $lock_period (the interval) and $number_attempts (number)
- Finally select the table login_attempts were username = ? AND tstamp > $valid_attempts ($valid_attempts = $now_tstamp - $lock_period)

if known username and rows >  $number_attempts -> Lock the account.
if unknow username Ban the IP

Thanks.

**Comment by ocram** [comment]
This is built-in and happens automatically:

https://github.com/delight-im/PHP-Auth#throttling-or-rate-limiting

**Comment by daebak74** [comment]
Great!!! Sorry for didn't found it.
